### ISSUE TITLE
It is not possible to export a scatterblot as a PDF document

### ISSUE THREAD

**Issue by sw0112358** [cox-labs/CoxLab_Bug_Reporting#101]
**Describe the bug**
It is not possible to export a Scatter plot as a PDF document

**To Reproduce**
1. Import a data set
2. Click on 'Scatter plot'
3. Click on 'Export image', choose PDF as file type and click on 'save'

**Expected behavior**
A saved PDF document of the Scatter plot

**Screenshots**
![image](https://github.com/user-attachments/assets/d848d1e8-5079-432f-8d0d-9720c422305f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2.1.1.0

**Additional context**
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at iTextSharp.text.pdf.PdfWriter.AddSimple(BaseFont bf)
   at iTextSharp.text.pdf.PdfContentByte.SetFontAndSize(BaseFont bf, Single size)
   at BaseLib.Graphic.PdfGraphics.SetFont(Font2 font) in C:\SourceCode\net7\net\BaseLib\Graphic\PdfGraphics.cs:line 325
   at BaseLib.Graphic.PdfGraphics.MeasureString(String text, Font2 font) in C:\SourceCode\net7\net\BaseLib\Graphic\PdfGraphics.cs:line 200
   at BaseLib.Forms.NumericAxisView.OnPaint(IGraphics g, Int32 xm, Int32 ym, Int32 width, Int32 height) in C:\SourceCode\net7\net\BaseLib\Forms\NumericAxisView.cs:line 258
   at BaseLib.Forms.NumericAxisView.OnPaint(IGraphics g, Int32 width, Int32 height) in C:\SourceCode\net7\net\BaseLib\Forms\NumericAxisView.cs:line 216
   at BaseLibS.Graph.Base.TableLayoutModel.OnPaint(IGraphics g, Int32 width, Int32 height) in C:\SourceCode\net7\net\BaseLibS\Graph\Base\TableLayoutModel.cs:line 167
   at BaseLibS.Graph.Base.BasicControlModel.Print(IGraphics g, Int32 width, Int32 height) in C:\SourceCode\net7\net\BaseLibS\Graph\Base\BasicControlModel.cs:line 117
   at BaseLib.Forms.Base.Printing.Print(IPrintable printable, String filename, Int32 width, Int32 height) in C:\SourceCode\net7\net\BaseLib\Forms\Base\Printing.cs:line 23
   at PluginBase.Scatter.ScatterPlotView.SaveAs() in C:\SourceCode\net7\net\PluginBase\Scatter\ScatterPlotView.cs:line 366
   at PluginBase.Scatter.ScatterPlotView.ExportImageButton_OnClick(Object sender, EventArgs e) in C:\SourceCode\net7\net\PluginBase\Scatter\ScatterPlotView.cs:line 437
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by WalterViegener** [comment]
That will be fixed with the upcoming release
