### ISSUE TITLE
Andromeda 2.0 Scoring throws an exception

### ISSUE THREAD

**Issue by nanomima** [cox-labs/CoxLab_Bug_Reporting#102]
**Describe the bug**
When Andromeda 2.0 Scoring is checked under Group-specific parameters using the Default fragmentation model type, an exception is thrown. 

************** Exception Text **************
System.Exception: Parameter does not exist: Default fragmentation model
   at MqApi.Param.Parameters.GetParam(String name)
   at MqApi.Param.Parameters.GetParamWithSubParams[T](String name)
   at MaxQuantLibS.Domains.Peptides.Basic.WorkflowModelGroupParams.GetAndromeda20DefaultModel(Parameters parameters) in C:\Users\bi\source\repos\net7\net\MaxQuantLibS\Domains\Peptides\Basic\WorkflowModelGroupParams.cs:line 3837
   at MaxQuantLibS.Domains.Peptides.Basic.WorkflowModelGroupParams.GetGroupParams(Parameters parameters) in C:\Users\bi\source\repos\net7\net\MaxQuantLibS\Domains\Peptides\Basic\WorkflowModelGroupParams.cs:line 767
   at MaxQuantLibS.Domains.Peptides.Basic.WorkflowModel.GetGroupParams(Parameters parameters) in C:\Users\bi\source\repos\net7\net\MaxQuantLibS\Domains\Peptides\Basic\WorkflowModel.cs:line 321
   at MaxQuantLib.Forms.MainFormData.<>c__DisplayClass189_0.<GetGroupParams>b__0() in C:\Users\bi\source\repos\net7\net\MaxQuantLib\Forms\MainFormData.cs:line 924
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at MaxQuantLib.Forms.MaxQuantMainForm.DispatcherInvoke(Action a) in C:\Users\bi\source\repos\net7\net\MaxQuantLib\Forms\MaxQuantMainForm.cs:line 309
   at MaxQuantLib.Forms.MainFormData.GetGroupParams(Parameters p) in C:\Users\bi\source\repos\net7\net\MaxQuantLib\Forms\MainFormData.cs:line 924
   at MaxQuantLib.Forms.MainFormData.UpdateMqParameters(Int32 numThreads, Boolean sendEmail, Func`2 getGroupParams) in C:\Users\bi\source\repos\net7\net\MaxQuantLib\Forms\MainFormData.cs:line 604
   at MaxQuantLib.Forms.MainFormData.StartButton_OnClick(Object sender, EventArgs e) in C:\Users\bi\source\repos\net7\net\MaxQuantLib\Forms\MainFormData.cs:line 802
   at BaseLibS.Graph.ButtonModel.OnMouseClick(BasicMouseEventArgs e) in C:\Users\bi\source\repos\net7\net\BaseLibS\Graph\ButtonModel.cs:line 52
   at BaseLib.Forms.Base.BasicControl.OnMouseClick(MouseEventArgs e) in C:\Users\bi\source\repos\net7\net\BaseLib\Forms\Base\BasicControl.cs:line 133
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**To Reproduce**
1. Go to 'Group-specific parameters' and choose the Andromeda tab
2. Check 'Andromeda 2.0 Scoring'
3. Press 'Start'

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MaxQuant 2.6.3

**Comment by WalterViegener** [comment]
We did not yet implement Andromeda 2.0 scoring. We will announce that in the release where it is included
