### ISSUE TITLE
Error in writing tables for TMT-based Tims-DDA search

### ISSUE THREAD

**Issue by gigi-mt** [cox-labs/CoxLab_Bug_Reporting#27]
Hello all.
I am running MQ 2.4 on Windows 11, with a single TMT-11plex acquired on a Bruker TIMS-TOF HT in DDA-PASEF mode. 
The run keeps crashing during the 'Writing Tables' step giving below error message (from proc folder). 
I already tried running the search from scratch, but the same error occurs. 
Is there anyone else who had similar issue or can provide a solution/workaround? 

Your help is greatly appreciated. 
Best,
G

id	0
start	25/04/2023 09:42:58
title	Writing_tables (09/23)
description	C:\Users\xyz.d\combined\proc Writing_tables 8 Writing_tables (09/23)  Process 23 0 C:\Users\xyz.d\combined C:\Users\xyz.d\mqpar.xml True 8
error	C:\Users\xyz.d\combined\proc Writing_tables 8 Writing_tables (09/23)  Process 23 0 C:\Users\xyz.d\combined C:\Users\xyz.d\mqpar.xml True 8_Object reference not set to an instance of an object._   at MaxQuantLibS.Domains.Peptides.Table.MsmsTable.FillReporterRatios(MsmsHit hit, DataRow2 row)__   at MaxQuantLibS.Domains.Peptides.Table.MsmsTable.FillReporters(MsmsHit hit, MaxQuantParams mqpar, DataRow2 row)__   at MaxQuantLibS.Domains.Peptides.Table.MsmsTable.Fill(IDataTable table, CombinedData combinedData, MaxQuantParams mqpar)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesMsms(String mqparFile, String combinedFolder, String txtFolder, String serFolder)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesTimsImpl(String combinedFolder, String txtFolder, String serFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesTims(String combinedFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Work.WriteTable.Calculation(String[] args, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)__   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)__   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)__   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end	25/04/2023 09:42:58

**Comment by pspealman** [comment]
I'm writing in with what I believe is the same problem. 

This is happening on both my Windows 11 (running MaxQuant 2.4.9) and Windows 10 (running MaxQuant 2.1.0) the mass spec is TMT-16plex. I am trying to run this with the mzTab table generation for submission to PRIDE database.

The error from Windows 11 / MaxQuant 2.4.9 is as follows:

`id	0
start	31/10/2023 19:15:23
title	Writing_tables (016/308)
description	C:\Gresham\ms_10262023\combined\proc Writing_tables 15 Writing_tables (016/308)  Process 23 0 C:\Gresham\ms_10262023\combined C:\Gresham\2023_09_11_Project_Carolino\Supplemental_files\ms_10252023\raw_ms\mqpar.xml False 15
error	C:\Gresham\ms_10262023\combined\proc Writing_tables 15 Writing_tables (016/308)  Process 23 0 C:\Gresham\ms_10262023\combined C:\Gresham\2023_09_11_Project_Carolino\Supplemental_files\ms_10252023\raw_ms\mqpar.xml False 15_Unable to cast object of type 'System.Int32' to type 'System.String'._   at BaseLibS.Table.TableUtils.WriteElement(BinaryWriter writer, Object o, ColumnType columnType)__   at MsLib.Util.DataTableWriterSerializer.WriteRow(BinaryWriter writer2, Object[] valuesObj)__   at MsLib.Util.DataTableWriterSerializer.WriteRow(DataRow2 row)__   at MsLib.Util.DataTableWriterSerializer.AddRow(DataRow2 row)__   at MaxQuantLibS.Domains.Peptides.Table.MzTabPsmSection.FillDda(IDataTable table, CombinedData combinedData, MaxQuantParams mqpar, String combinedFolder)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesMzTabPsmSection(String mqparFile, String combinedFolder, String txtFolder, String serFolder)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesImpl(String combinedFolder, String txtFolder, String serFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTables(String combinedFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Work.WriteTable.Calculation(String[] args, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)__   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)__   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)__   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end	31/10/2023 19:15:30
`

**Comment by witszymanski** [comment]
Having the same problem. 

- TimsTof Pro, DDA-PASEF method
- TMT 9-plex
- error on writing tables
- 2 separate Windows 11 PCs 

For me, none of the versions below worked:

- 2.4.3.0
- 2.4.7.0
- 2.4.9.0

I also tried some older versions, and with no success.

**Comment by ShwetaCh** [comment]
Hi,

I'm seemingly having the same problem on MaxQuant_v2.3.1.0 on Windows 10, has anyone figured this out or found a work around?

I do see that I've all the required txt files, and the run seems to be complete otherwise (it ran for 4 days before crashing for an input set of ~700GB)

Complete example error below, the run has 7 such error files related to writing_tables. I had selected to write all possible tables. I can't tell if the results are safe to use, since they look complete otherwise and it failed at the very last step while being successful even at the penultimate step of "Prepare_writing_tables 11.finished"?

Any comments are highly appreciated.
  
Best,
Shweta

```id	0
start	01/01/2024 16:52:44
title	Writing_tables (0029/3332)
description	C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\combined\proc Writing_tables 28 Writing_tables (0029/3332)  Process 23 0 C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\combined C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\mqpar.xml False 28
error	C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\combined\proc Writing_tables 28 Writing_tables (0029/3332)  Process 23 0 C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\combined C:\Users\platform\DATA\public\CCLE\MSV000085836\raw\raw\mqpar.xml False 28_Object reference not set to an instance of an object._   at BaseLibS.Num.ArrayUtils.SubArray[T](IList`1 array, IList`1 indices)__   at MaxQuantLibS.Domains.Peptides.Dependent.DependentIdentifications.GetRowByScanNumber(Int32 scanNumber)__   at MaxQuantLibS.Domains.Peptides.Table.MsmsScansTable.FillTable(IDataTable table, String rawFile, Int32 rawFileIndex, CombinedData combinedData, ProteinSet proteinSet, MaxQuantParams mqpar, GroupParams gp)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.FillMsmsScansTable(String filenameTxt, String filenameSer, MaxQuantParams mqpar, Int32 index, String combinedFolder)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteRemainingTables(Int32 jobIndex, String mqparFile, String combinedFolder, String txtFolder, String serFolder)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTablesImpl(String combinedFolder, String txtFolder, String serFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Table.TableUtilsP.WriteTables(String combinedFolder, String mqparFile, Int32 taskIndex)__   at MaxQuantLibS.Domains.Peptides.Work.WriteTable.Calculation(String[] args, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)__   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)__   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)__   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end	01/01/2024 16:52:54
```

**Comment by witszymanski** [comment]
We may not get any answer... In my case, I was not able to solve the problem. I ended up remeasuring all the samples on Exploris and everything worked out smoothly. 

It's a bummer, this issue.

**Comment by ShwetaCh** [comment]
Indeed a bummer!
Also, I just had another Label Free experiment run also fail with same errors. Does seem like it has to do with writing those mzTab tables, but I can't tell which exact table it doesn't want to write.

**Comment by WalterViegener** [comment]
Dear all, 
In case the issue is still there, please create a zip folder of everything I need (name it with your github username) and I will try to finally solve the issue. Please upload it [here. ](https://datashare.biochem.mpg.de/s/PpeK7EU1EUkDInf). To make the analysis as easy as possible i need the raw file (ideally just 1), fasta file(s) and mqpar file.
Best, 
Walter
