### ISSUE TITLE
[MaxQuant (Version 2.4.2.0)] An protein assembly error for DDA FAIMS data with Re-quantify on

### ISSUE THREAD

**Issue by FumikoMatsuzaki** [cox-labs/CoxLab_Bug_Reporting#31]
**Describe the bug**
MaxQuant (Version 2.4.2.0) throws an error while assembling proteins for DDA FAIMS data labeled at MS1-level with “Re-quantify” option enabled.

Here are the contents of the “Assembling_proteins XXX.error.txt” and “Assembling_proteins XXX.comment.txt” files generated in the “proc” directory for two separate runs.

[Case 1]

Assembling_proteins 0180.error.txt
~~~~~~~~
id	0
start	21/05/2023 05:21:30
title	Assembling_proteins (01/80)
description	H:\combined\proc Assembling_proteins 0 Assembling_proteins (01/80)  Process 46 0 H:\combined H:\mqpar.xml 0
error	H:\combined\proc Assemblissembling_proteins (01/80)  Process 46 0 H:\combined H:\mqpar.xml 0_Object reference not set to an instance of an object._   at MaxQuantLibS.Domains.Peptides.Features.ReQuantResult.ContainsIsotopeIndex(Int32 id)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.AddSearchEngineHit(ModificationSpecificPeptide msp, MsmsHit msmsHit, GroupParams param, IList`1 p, Int32 fileIndex, Int32 faimsIndex, QueryType type, Int32 multipletId, Int32 isotopeId, Multiplet m, IsotopeCluster isotopeCluster, Double retentionTime, GenericPeakListLayerData peakList, Double mz, ReQuantResult reQuantResult, NeucodeQuantResult ncQuantResult, Dictionary`2 addtlResults, Boolean isMs3, Boolean isIsobaric, Boolean isTims, Int32 imsMean, Double imsDip, Int32 imsMin, Int32 imsMax, Double ccsMean, Double ccsMin, Double ccsMax)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.AddSearchEngineHit(IdentifiedPeptide ip, MsmsHit msmsHit, GroupParams param, IList`1 p, Int32 fileIndex, Int32 faimsIndex, QueryType type, Int32 multipletId, Int32 isotopeId, Multiplet multiplet, IsotopeCluster isotopeCluster, Double retentionTime, GenericPeakListLayerData peakList, Double mz, ReQuantResult reQuantificationResult, NeucodeQuantResult ncQuantResult, Dictionary`2 addtlResults, Boolean isMs3, Boolean isIsobaric, Boolean isTims, Int32 imsMean, Double imsDip, Int32 imsMin, Int32 imsMax, Double ccsMean, Double ccsMin, Double ccsMax)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.ProcessPeptides(RankPredictionModel ipm, MaxQuantParams mqpar, Int32 fileIndex, Int32 faimsIndex, Dictionary`2 proteinIdToGroupIndex, GenericPeakListLayerData peakList, RawFileLayer rf, MsmsData msmsData, IdentifiedPeptide[] identifiedPeptides, String[] peptideSequences, ReQuantResult reQuantResult, NeucodeQuantResult ncQuantResult, ProteinSet proteinSet, String basePath, Int32[] topIntens, IDictionary`2 cachedAndromedaScoresForMassAnalyzer)__   at MaxQuantLibS.Domains.Peptides.Data.GenericRunLayer.ProcessSearchEnginePeptides(RankPredictionModel ipm, Int32 fileIndex, Int32 faimsIndex, Dictionary`2 proteinIdToGroupIndex, IdentifiedPeptide[] peptides, String[] peptideSequences, ProteinSet proteinSet, GroupParams gp, MaxQuantParams mqpar, Int32[] topIntens, IDictionary`2 cachedAndomedaForMassAnalyzer)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessSearchEnginePeptides(Dictionary`2 proteinIdToGroupIndex, IdentifiedPeptide[] peptides, ProteinSet proteinSet, MaxQuantParams mqpar, IDictionary`2 andromedaScorePositioningCache, Responder responder, Int32 f1)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessPeptides(String combinedFolder, MaxQuantParams mqpar, Int32 fileIndex, IDictionary`2 andromedaScorePositioningCache, Responder responder)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessPeptidesX(String combinedFolder, String mqparFile, Int32 jobIndex, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.ProteinAssembler.Calculation(String[] args, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)__   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)__   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)__   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end	21/05/2023 05:21:42
~~~~~~~~

Assembling_proteins 0180.comment.txt
~~~~~~~~
0 006
~~~~~~~~

[Case 2]

Assembling_proteins 0116.error.txt
~~~~~~~~
id	0
start	21/05/2023 08:21:12
title	Assembling_proteins (01/16)
description	H:\combined\proc Assembling_proteins 0 Assembling_proteins (01/16)  Process 46 0 H:\combined H:\mqpar.xml 0
error	H:\combined\proc Assembling_proteins 0 Assembling_proteins (01/16)  Process 46 0 H:\combined H:\mqpar.xml 0_Object reference not set to an instance of an object._   at MaxQuantLibS.Domains.Peptides.Features.ReQuantResult.ContainsIsotopeIndex(Int32 id)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.AddSearchEngineHit(ModificationSpecificPeptide msp, MsmsHit msmsHit, GroupParams param, IList`1 p, Int32 fileIndex, Int32 faimsIndex, QueryType type, Int32 multipletId, Int32 isotopeId, Multiplet m, IsotopeCluster isotopeCluster, Double retentionTime, GenericPeakListLayerData peakList, Double mz, ReQuantResult reQuantResult, NeucodeQuantResult ncQuantResult, Dictionary`2 addtlResults, Boolean isMs3, Boolean isIsobaric, Boolean isTims, Int32 imsMean, Double imsDip, Int32 imsMin, Int32 imsMax, Double ccsMean, Double ccsMin, Double ccsMax)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.AddSearchEngineHit(IdentifiedPeptide ip, MsmsHit msmsHit, GroupParams param, IList`1 p, Int32 fileIndex, Int32 faimsIndex, QueryType type, Int32 multipletId, Int32 isotopeId, Multiplet multiplet, IsotopeCluster isotopeCluster, Double retentionTime, GenericPeakListLayerData peakList, Double mz, ReQuantResult reQuantificationResult, NeucodeQuantResult ncQuantResult, Dictionary`2 addtlResults, Boolean isMs3, Boolean isIsobaric, Boolean isTims, Int32 imsMean, Double imsDip, Int32 imsMin, Int32 imsMax, Double ccsMean, Double ccsMin, Double ccsMax)__   at MaxQuantLibS.Domains.Peptides.Search.Identifications.ProcessPeptides(RankPredictionModel ipm, MaxQuantParams mqpar, Int32 fileIndex, Int32 faimsIndex, Dictionary`2 proteinIdToGroupIndex, GenericPeakListLayerData peakList, RawFileLayer rf, MsmsData msmsData, IdentifiedPeptide[] identifiedPeptides, String[] peptideSequences, ReQuantResult reQuantResult, NeucodeQuantResult ncQuantResult, ProteinSet proteinSet, String basePath, Int32[] topIntens, IDictionary`2 cachedAndromedaScoresForMassAnalyzer)__   at MaxQuantLibS.Domains.Peptides.Data.GenericRunLayer.ProcessSearchEnginePeptides(RankPredictionModel ipm, Int32 fileIndex, Int32 faimsIndex, Dictionary`2 proteinIdToGroupIndex, IdentifiedPeptide[] peptides, String[] peptideSequences, ProteinSet proteinSet, GroupParams gp, MaxQuantParams mqpar, Int32[] topIntens, IDictionary`2 cachedAndomedaForMassAnalyzer)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessSearchEnginePeptides(Dictionary`2 proteinIdToGroupIndex, IdentifiedPeptide[] peptides, ProteinSet proteinSet, MaxQuantParams mqpar, IDictionary`2 andromedaScorePositioningCache, Responder responder, Int32 f1)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessPeptides(String combinedFolder, MaxQuantParams mqpar, Int32 fileIndex, IDictionary`2 andromedaScorePositioningCache, Responder responder)__   at MaxQuantLibS.Domains.Peptides.ProteinTasks.ProteinAssembly.ProcessPeptidesX(String combinedFolder, String mqparFile, Int32 jobIndex, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.ProteinAssembler.Calculation(String[] args, Responder responder)__   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)__   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)__   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)__   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
end	21/05/2023 08:21:24
~~~~~~~~

Assembling_proteins 0116.comment.txt
~~~~~~~~
0 006
~~~~~~~~

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
If you need more details, I would be pleased to share them.

Sincerely,
Fumiko

**Comment by fedefratini** [comment]
I get the same error (look at FAIMS-DDA protein assembling error #50 )

did you get any help?

thnaks

Federica

**Comment by WalterViegener** [comment]
Dear all we do not support requantify and MBR for FAIMS. It should nevertheless work if you split the CVs and then select Standard as runtype. If not, let me know
