### ISSUE TITLE
MQ2.4.2.0 DIA vs .wiff files crash

### ISSUE THREAD

**Issue by tretyacv** [cox-labs/CoxLab_Bug_Reporting#41]
**Describe the bug**
Running any MaxDIA pipeline using .wiff as input fails on Feature detection step:
```
Configuring
Assemble run info
Finish run info
Testing fasta files
Preparing searches
Generate libraries
Feature detection

Unhandled Exception: System.Exception: Exception during execution of external process: 12508 Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\slavat.WISMAIN\Dow       nloads\T8_kin_1_\p0\T8_kin_1_.bg.dia0'.
File name: 'C:\Users\slavat.WISMAIN\Downloads\T8_kin_1_\p0\T8_kin_1_.bg.dia0'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at BaseLibS.Util.FileUtils.GetBinaryReader(String path)
   at MaxQuantLibS.Domains.Peptides.Features.FeatureDetectionUtil.DetectFeatures(MaxQuantParams mqpar, Int32 taskIndex, Boolean positiveMode, Responder responder, Int32 batchBegin, Int32 batchEnd       )
   at MaxQuantLibS.Domains.Peptides.Features.FeatureDetectionUtil.DetectFeatures(String mqparFile, Int32 taskIndex, Boolean positiveMode, Responder responder, Int32 batchBegin, Int32 batchEnd)
   at MaxQuantLibS.Domains.Peptides.Work.FeatureDetection.Calculation(String[] args, Responder responder)
   at MaxQuantLibS.Domains.Peptides.Work.MaxQuantWorkDispatcherUtil.PerformTask(Int32 taskType, String[] args, Responder responder)
   at MaxQuantLibS.Base.MaxQuantUtils.Run(Int32 softwareId, Int32 taskType, String[] args, Responder responder)
   at MaxQuantTaskCore.Program.Function(String[] args, Responder responder)
   at Utils.Util.ExternalProcess.Run(String[] args, Boolean debug)
   at MaxQuantTaskCore.Program.Main(String[] args)

   at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

``` 

Same error happens in GUI

**To Reproduce**
1. Go to 'any DIA dataset in .wiff format https://www.ebi.ac.uk/pride/archive/projects/PXD036444'
2. Click on 'run MaxDIA in discovery mode with fasta/evidence/msms files from MQ web'
3. See error

**Expected behavior**
Not crashing, this does not happen when .raw files are used as input

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**

**Comment by tretyacv** [comment]
the issue also reported here - https://groups.google.com/g/andromeda-list/c/FgmIHqVAvPQ

**Comment by dtabb73** [comment]
I had the same experience with the feature detector in MaxQuant 2.5.0.0 using WIFF files from PXD002965, though the error was "could not find file".
![image](https://github.com/cox-labs/CoxLab_Bug_Reporting/assets/25929598/4538d41e-ca3d-4c88-8d1e-f8e581c81c68)

**Comment by zznx** [comment]
![image](https://github.com/user-attachments/assets/e55a521f-060c-42c7-87f1-ff614cad7794)
Is it the same problem? Is it solved yet? (wiff and IDA)

**Comment by dtabb73** [comment]
Have you tried with version 2.6.2.0?  I have not updated from 2.5.0.0, but I was unable to get MaxDIA in MaxQuant 2.5.0.0 to read WIFFs from either of two IDA ProteomeXchange projects.

**Comment by zznx** [comment]
I used MaxQuant_v2.6.1.0, but it didn't work.

**Comment by wangss3** [comment]
Same issue with wiff files (version 2.6.5.0).

But my orbitrap raw data worked fine.

**Comment by WalterViegener** [comment]
We do not support that yet
