### ISSUE TITLE
Perseus 2.0.11 will not allow any plots to open or selection of other matrices by clicking on them.

### ISSUE THREAD

**Issue by vcoyne1** [cox-labs/CoxLab_Bug_Reporting#87]
**Describe the bug**

I saved the previous session as a .sps file. All was functioning appropriately. On opening the file to continue working on the analysis, I was confronted with the following:

Unhandled exception has occurred in your application. If you click Continue, the application will ignore the error and attempt to continue. If you click Quit, the application will close immediately.

Object reference not set to an instance of an object.

So when I click continue, the application continues, but selecting any of the plots or matrixes does not work. Attempting to plot a new  plot (eg heatmap using existing matrix) is not functional (no data is shown in the dialog box for selection box for inclusion in the heatmap, etc).

Exiting from the application, does not resolve the issue, neither does saving the data to a new .sps file. 

Here is the info that is listed in the error box that comes up. I have no idea what this means.
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PluginBase.Scatter.ScatterPlotView.GetData(Double[]& x, Double[]& y, Double[]& z, String[]& label, Int32& index)
   at PluginBase.Scatter.ScatterPlotView.CalcRanges()
   at PluginBase.Scatter.ScatterPlotView.InitScatterPlotData()
   at PluginBase.Scatter.ScatterPlotDataView.YDataComboBoxSelectedIndexChanged()
   at PluginBase.Scatter.ScatterPlotDataView.YBox_OnSelectionChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PluginBase.Scatter.ScatterPlotDataView.Init()
   at PluginBase.Scatter.ScatterPlotControl.CreateDataPanel()
   at PluginBase.Scatter.ScatterPlotControl..ctor(ScatterPlotResult result, Action`1 createNewMatrix)
   at PluginBase.Scatter.ScatterPlotResult.CreateUiElement(Action`1 updateStatusLabel, Action`1 newMatrix)
   at PerseusLib.Forms.DataMainControl.SetResultControl(IAnalysisResult result, Action`1 newData)
   at PerseusLib.Forms.PerseusMainControl.FillSessionInfo(PerseusWorkflowModel si)
   at PerseusLib.Forms.PerseusMainControl.LoadSession(String fileName1, Action`1 showMessage)
   at PerseusLib.Forms.PerseusMainForm.OpenMenuItem_OnClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PerseusGui
    Assembly Version: 1.6.13.0
    Win32 Version: 1.6.13.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PerseusGui.exe
----------------------------------------
CefSharp.Core
    Assembly Version: 63.0.3.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/CefSharp.Core.DLL
----------------------------------------
PerseusLib
    Assembly Version: 2.0.11.0
    Win32 Version: 2.0.11.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PerseusLib.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
BaseLibS
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/BaseLibS.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
CefSharp
    Assembly Version: 63.0.3.0
    Win32 Version: 63.0.3.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/CefSharp.DLL
----------------------------------------
PerseusLibS
    Assembly Version: 2.0.11.0
    Win32 Version: 2.0.11.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PerseusLibS.DLL
----------------------------------------
PerseusApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PerseusApi.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FloatingTabs
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/FloatingTabs.DLL
----------------------------------------
BaseLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/BaseLib.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
Utils
    Assembly Version: 1.5.8.0
    Win32 Version: 1.5.8.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/Utils.DLL
----------------------------------------
PluginBase
    Assembly Version: 1.6.2.2
    Win32 Version: 1.6.2.2
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginBase.DLL
----------------------------------------
PluginInterop
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginInterop.DLL
----------------------------------------
PerseusPluginLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PerseusPluginLib.DLL
----------------------------------------
PluginBase2
    Assembly Version: 1.6.1.3
    Win32 Version: 1.6.1.3
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginBase2.DLL
----------------------------------------
PluginBasic3
    Assembly Version: 1.6.10.50
    Win32 Version: 1.6.10.50
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginBasic3.DLL
----------------------------------------
PluginCoexpression
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginCoexpression.DLL
----------------------------------------
PluginCyTOF
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginCyTOF.DLL
----------------------------------------
PluginDEanalysis
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginDEanalysis.DLL
----------------------------------------
PluginIsobaricLabeling
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginIsobaricLabeling.DLL
----------------------------------------
PluginLearning
    Assembly Version: 1.6.10.50
    Win32 Version: 1.6.10.50
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginLearning.DLL
----------------------------------------
PluginMetis
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginMetis.DLL
----------------------------------------
PluginMultiVolcano
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginMultiVolcano.DLL
----------------------------------------
PluginNetwork
    Assembly Version: 1.6.10.43
    Win32 Version: 1.6.10.43
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginNetwork.DLL
----------------------------------------
PluginPHOTON
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginPHOTON.DLL
----------------------------------------
PluginProteomicRuler
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginProteomicRuler.DLL
----------------------------------------
PluginTimeSeries
    Assembly Version: 1.6.10.0
    Win32 Version: 1.6.10.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/PluginTimeSeries.DLL
----------------------------------------
NumPluginBase
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/NumPluginBase.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
UtilsWf
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Perseus_2.0.11/Perseus%202.0.11/bin/UtilsWf.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Your assistance with this will be most appreciated as the analysis includes a great deal of work that is now essentially useless.

Thanks

**Comment by WalterViegener** [comment]
Hi, 
Could you please upload your .sps file [here](https://datashare.biochem.mpg.de/s/VLGlyqPXonRla9S)? It will be handled confidentially.

**Comment by WalterViegener** [comment]
Dear [vcoyne1](https://github.com/vcoyne1),
Dou you still encounter the issue?
